### ISSUE TITLE
Requirements :P

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio-s3#1]
I have no idea what you are trying to accomplish here but I have a small ZIO-AWS wrapper myself, so let me list off what I have needed :)

- The AWS SDK reads implicit credentials, which is essentially never what you want. Make sure a client is passed credentials
- You can fetch S3 files onto disk or as an `OutputStream`. The latter is very useful for larger files
- There is a `Region` class but you can make invalid instances of it, which will blow things up with runtime exceptions

I solved the `Region` issue like so:

```scala
def region(r: String): Option[Region] =
    Option(Region.of(r)).filter(Region.regions.contains(_))
```

It would be sweet if the S3 wrapper could stream me file contents line-by-line (i.e. for CSV or line-break separated JSONs).

**Comment by regis-leray** [comment]
Thank a lot for your feedback. We will do our best to have an idiomatic `zio-s3` library. You are welcome to contribute.
