### ISSUE TITLE
Add another function that returns zio.Stream for listing objects in s3

### ISSUE THREAD

**Issue by afsalthaj** [zio/zio-s3#11]
With the help of `listObjects` and `getNextObjects`, could we consider having a third function that returns a `Stream[S3ObjectListing]` ?

It will be helpful for the users if zio-S3 handles it instead of figuring out themselves.

**Comment by regis-leray** [comment]
we already have this combinator available

```
 def paginate(initialListing: S3ObjectListing): S3Stream[S3ObjectListing]
```

**Comment by regis-leray** [comment]
I need to start to write some meanful documentation for this project :)
