### ISSUE TITLE
Need a way of creating a client that is inside a EC2 instance with a IAM role. 

### ISSUE THREAD

**Issue by sken77** [zio/zio-s3#133]
Not sure if this can be sorted without changing the code, but is there a way of creating a client that takes the credentials from role?
Also, there isn't a zio-s3 group chat where we can discuss anything. ping me your discord tag so we can talk in case we need to do changes I can submit them myself
Thanks

**Comment by regis-leray** [comment]
hello, currently zio-s3 only provide a pretty straigtforward way to handle credentials and we dont rely on credentials strategy to rely credentials.
Which i think you are refering from the documentation
https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-roles.html

Are you suggesting to have the same behaviour ?

heere my tag in discord channel
regis#5084

**Comment by sken77** [comment]
Yeah particularly this part

`The final step in the default provider chain is available only when running your application on an Amazon EC2 instance. However, it provides the greatest ease of use and best security when working with Amazon EC2 instances. You can also pass an InstanceProfileCredentialsProvider instance directly to the client constructor to get instance profile credentials without proceeding through the entire default provider chain.`

`InstanceProfileCredentialsProvider` doesn't have a get awsaccessId/secret . 

Im using the old `import com.amazonaws.auth.DefaultAWSCredentialsProviderChain` and getting the access id and secret from there. but we are having issues with it in EC2.

**Comment by regis-leray** [comment]
that should work
```
  def fromInstanceProfile: ZIO[Blocking, InvalidCredentials, S3Credentials] = effectBlocking{
    val creds = InstanceProfileCredentialsProvider.builder()
      .build().resolveCredentials()
    S3Credentials(creds.accessKeyId(), creds.secretAccessKey())
  }.mapError(e => InvalidCredentials(e.getMessage))
```

can you explain how do you configure your credentials to run your application locally?
