### ISSUE TITLE
No support for EKS IAM

### ISSUE THREAD

**Issue by sken77** [zio/zio-s3#146]
Our Team had a problem using this library, and pin point the problem to this issue: 

https://github.com/aws/aws-sdk-java-v2/issues/1470

The solution was to add the sts dependency in order to enable [WebIdentity](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.html) and then pass the `DefaultCredentialsProvider`

```
val builder = S3AsyncClient
              .builder()
              .credentialsProvider(DefaultCredentialsProvider.create())
              .region(region)
            uriEndpoint.foreach(builder.endpointOverride)
            builder.build()
```

So the solution would be to allow to create a layer passing a CredentialsProvider or allow a constructor that only takes region and calls `DefaultCredentialsProvider.create()`, theres also the sts dependency if we want to add it or not, which seems like we should

Please let me know what you decide and i can help with a PR.

**Comment by regis-leray** [comment]
@sken77 i provided a way to expose AwsCredentialsProvider
https://github.com/zio/zio-s3/blob/master/src/main/scala/zio/s3/settings.scala

So you just need to add this missing one

```scala
val fromWebIdentity: IO[InvalidCredentials, S3Credentials] =
    load(ZManaged.effect(WebIdentityTokenFileCredentialsProvider.create()))(p => IO(p.resolveCredentials()))
```

more explanations how to use it
https://zio.github.io/zio-s3/docs/quickstart/quickstart_index#credentials

**Comment by sken77** [comment]
@regis-leray thanks for responding. wont there be any issues when casting the creds into a Static holder? cos i think it will eventually time out on the default session length. and new credentials would need to be retrieved again. not sure if other providers work like that as well

**Comment by regis-leray** [comment]
i dont think there will be an issue `WebIdentityTokenFileCredentialsProvider.create()`, this static holder are only a description of how to fetch nothing is computed at the moment. Only when we are running the program.

**Comment by sken77** [comment]
Oh yeah, i get that part. i'm just wondering if the S3AsyncClient from AWS retrieves credentials more than once, particularly after creation. and if the output from `WebIdentityTokenFileCredentialsProvider` would be different. as i said, roles do expire, so i'm assuming that for this provider it is. We haven't tested with this expiring tho.

Also, should i inlcude the sts dependency in sbt?

**Comment by regis-leray** [comment]
We could add this dependency in sbt as optional, and put a not in the source code

**Comment by regis-leray** [comment]
```
libraryDependencies += "group id" % "artifact id" % "version" % "optional"
```
