### ISSUE TITLE
Remove region check

### ISSUE THREAD

**Issue by PawelJ-PL** [zio/zio-s3#194]
Hi,

What do you think about allowing the use of any region, instead of using a limited list of options? The current solution (https://github.com/zio/zio-s3/blob/1893e629f7c02833669d650b853a1b41cdf1a5f9/src/main/scala/zio/s3/settings.scala#L99) makes it impossible to use other (than AWS) implementations of S3.

**Comment by regis-leray** [comment]
S3 is a AWS product. Can you explain your problem you are facing ?
Currently the region sdk is not safe since you can create an invalid region
```scala
Region("invalid")
```

**Comment by PawelJ-PL** [comment]
I would like to use library with onprem OpenStack object storage (Swift) with S3 compatible API, which has configured single region `openstack`. I can see, that OVH has S3 compatible Swift in their offer with different regions.

**Comment by regis-leray** [comment]
i could add a unsafe method.

**Comment by regis-leray** [comment]
@PawelJ-PL i add a unsafe method :)

**Comment by PawelJ-PL** [comment]
Thanks @regis-leray
