### ISSUE TITLE
`fromWebIdentity` based authentication does not work

### ISSUE THREAD

**Issue by yurikpanic** [zio/zio-s3#208]
When `S3Credentials.fromWebIdentity` is used (either directly or via `fromAll`, when all other methods in the chain failed) it calls `WebIdentityTokenFileCredentialsProvider.create().resolveCredentials()` under the hood. And populates `S3Credentials` case class with values from `AwsCredentials` interface returned by this `resolveCredentials` method. 

But it looks like it's not enough to copy just key and secret in this case. The instance that is returned by `resolveCredentials` is an instance of `AwsSessionCredentials`, which holds `accessKey`, `secretKey` _and_ `sessionToken`. So, just passing an instance of `StaticCredentialsProvider` with values of key and secret copied from `resolveCredentials` result is not enough in this case. Authorization fails.

But it works, if we create the s3 client by passing an instance created by `WebIdentityTokenFileCredentialsProvider.create()` to `.credentialsProvider` builder method.

**Comment by yurikpanic** [comment]
BTW, I'm not sure, if that it's a correct way to just call `resolveCredentials` once when we provide a S3 dependency in this case. According to comments in `WebIdentityTokenFileCredentialsProvider` it creates a thread, that refreshes the token in background. So, perhaps requests may start failing after the token is expired, even if we pass it through the S3Credentials instance somehow.

**Comment by regis-leray** [comment]
I will look into how to resolve this issue. thanks again to report it !

**Comment by regis-leray** [comment]
this is fixed

**Comment by regis-leray** [comment]
@yurikpanic release is available 0.3.2 :)
