### ISSUE TITLE
Stub layer's Any type for E is unexpected

### ISSUE THREAD

**Issue by gannicottb** [zio/zio-s3#222]
While using this library's stub layer for writing specs, I noticed something odd.
```
def stub(path: ZPath): ZLayer[Blocking, Any, S3] =
    ZLayer.fromFunction(Test.connect(path))
```

The `E` type is `Any`, which is a widening from the `E` of ZLayer.fromFunction, which is `Nothing` - the function provided to `fromFunction` is meant to be total. The consequence of this is that it is impossible to eliminate the error type of the stub layer with `.orDie` (as we do for our other test layers). I see that your in your tests you use `.mapError` to transform the `Any` to `TestFailure[Any]`, but that's not ergonomic for our code. I'm just curious about the motivation behind this design decision; maybe I'm just confused.

Thanks!

**Comment by regis-leray** [comment]
Wrong IDE type resolution :)
Thanks again for reporting the issue.

**Comment by regis-leray** [comment]
#223

**Comment by gannicottb** [comment]
Wow, thank you so much for the quick turnaround! :)
