### ISSUE TITLE
0.3.3 not in Central

### ISSUE THREAD

**Issue by sirocchj** [zio/zio-s3#226]
Hey, when trying to upgrade to 0.3.3 I noticed that the release went all through into sonatype releases (see https://oss.sonatype.org/service/local/repositories/releases/content/dev/zio/zio-s3_2.13/0.3.3/zio-s3_2.13-0.3.3.pom) but it's not yet in Maven Central https://repo1.maven.org/maven2/dev/zio/zio-s3_2.13/ (and it's more than 18hrs now)

I noticed that sonatype had a few issues over yesterday and today (see https://status.maven.org/)... so you may want to keep an eye on this and maybe even consider releasing again

**Comment by regis-leray** [comment]
thanks for letting me know. i will trigger again a new release

**Comment by sirocchj** [comment]
You're welcome! 🙂 Hope it solves

**Comment by regis-leray** [comment]
i m releasing 0.3.4

**Comment by sirocchj** [comment]
Thanks! Upgrading to 0.3.4, closing this.
