### ISSUE TITLE
multipartUpload throws software.amazon.awssdk.services.s3.model.S3Exception

### ISSUE THREAD

**Issue by serrufSe** [zio/zio-s3#262]
Hello
I have found that multipartUpload can throw 
```
A checked error was not handled.
software.amazon.awssdk.services.s3.model.S3Exception: Unable to execute HTTP request: null
```
for parallel upload (parallelism > 1)
[file for reproduce](https://github.com/zio/zio-s3/files/7200688/N-906.pdf)
```
  val ak = ???
  val sk = ???
  val uri = ???
  val filePath = ???
  val stream = ZStream.fromFile(filePath).provideLayer(Blocking.live)
  val s3Layer = s3.live(Region.EU_CENTRAL_1, AwsBasicCredentials.create(ak, sk), Some(URI.create(uri)))
  val app = multipartUpload("temp", "test", stream)(2)

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = app.provideLayer(s3Layer).exitCode
```
version
"dev.zio" %% "zio-s3" % "0.3.7"

**Comment by regis-datapassports** [comment]
Hello can you please provide the full stacktrace 
thank you

**Comment by regis-leray** [comment]
Hello can you please provide the full stacktrace
thank you

**Comment by regis-leray** [comment]
i used your file i was able to upload on a amazon s3 storage

```scala
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials

import java.io.FileInputStream
import java.nio.file.Paths
import software.amazon.awssdk.regions.Region
import zio.blocking.Blocking
import zio.stream.ZStream
import zio.{Runtime}

 val value = multipartUpload(
            "regis-leray-bucket-1",
            "upload/N-906.pdf",
            ZStream.fromInputStream(
              new FileInputStream(Paths.get("/Users/regis/Desktop/N-906.pdf").toFile)
            )
          )(2).provideLayer( Blocking.live ++ live(
      Region.CA_CENTRAL_1,
      AwsBasicCredentials.create("***", "***")
    ))

    Runtime.default.unsafeRun(value)
````

**Comment by regis-leray** [comment]
are you sure about your file path ?

**Comment by serrufSe** [comment]
[stacktrace.txt](https://github.com/zio/zio-s3/files/7205427/stacktrace.txt)

I am pretty sure about file path 
With parallelism = 1 everything fine

**Comment by regis-datapassports** [comment]
You have a timeout in your stacktrace 
```Caused by: io.netty.handler.timeout.ReadTimeoutException```

Look my code im using `parallelism = 2`, can you please try my code on your side ?

What is the provider you are using for s3 in your code you have a custom `uri`

**Comment by regis-leray** [comment]
You have a timeout in your stacktrace
```
Caused by: io.netty.handler.timeout.ReadTimeoutException
```
Look my code im using `parallelism = 2`, can you please try my code on your side ?

What is the provider you are using for s3 in your code you have a custom uri

**Comment by serrufSe** [comment]
You are right about ReadTimeoutException, i have not noticed :upside_down_face:
I use my local minio as s3 service, maybee it has some restriction for parallel multipartUpload
Thank for help

**Comment by regis-leray** [comment]
we are using minio in our integration test, here a test with `parallelism = 4`

https://github.com/zio/zio-s3/blob/master/src/test/scala/zio/s3/S3Test.scala#L283

**Comment by regis-leray** [comment]
im closing the issue, if you find other problem dont hesitate to reopen
