### ISSUE TITLE
Add a possibility to handle session credentials in `live`. 

### ISSUE THREAD

**Issue by Wosin** [zio/zio-s3#353]
There is currently a method called `def live(region: Region, credentials: AwsCredentials, uriEndpoint: Option[URI] = None)` which will only use the `accessKeyId` and `secretAccessKey` when authenticating. This makes it impossible to use with e.g. `SessionAwsCredentials` which will return cryptic errors about keys not being present in the registry.

We could either add a special handling for `SessionAwsCredentials` or add a note in the documentation about this behavior.

**Comment by regis-leray** [comment]
Hello, 
You could add a provider in https://github.com/zio/zio-s3/blob/series/2.x/src/main/scala/zio/s3/providers.scala
and also you can use this

https://github.com/zio/zio-s3/blob/series/2.x/src/main/scala/zio/s3/Live.scala#L234

**Comment by Wosin** [comment]
Yeah, but I You pass `AwsSessionCredentials` which will be possible because they extend `AwsCredentials` it will ignore `sessionToken` and the authentication will fail.

**Comment by regis-leray** [comment]
Good catch so please create a provider, and it will work
https://github.com/zio/zio-s3/blob/series/2.x/src/main/scala/zio/s3/providers.scala#L8

```scala
def session(accessKeyId: String, secretAccessKey: String, sessionToken: String): UManaged[AwsCredentialsProvider] =
    ZManaged.succeedNow[AwsCredentialsProvider](new AwsCredentialsProvider {
      override def resolveCredentials(): AwsCredentials = AwsSessionCredentials.create(accessKeyId, secretAccessKey, sessionToken)
    })
```

**Comment by regis-leray** [comment]
I solved your problem, you can even use `live()` with aws session credentials :)

https://github.com/zio/zio-s3/pull/354

**Comment by regis-leray** [comment]
https://github.com/zio/zio-s3/releases/tag/v0.4.2
