### ISSUE TITLE
Fails to import build with Scala 3

### ISSUE THREAD

**Issue by wheatandtares** [zio/zio-s3#395]
When I compile with 
```
val scalaVersion = "3.2.2"
```
And dependency
```
"dev.zio"     %% "zio-s3"                 % "0.4.2.1",
```

I'm getting an error  

```
2023.01.27 10:40:18 INFO  [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/..."), "..."):
2023.01.27 10:40:18 INFO  [error]    org.scala-lang.modules:scala-collection-compat _3, _2.13
```

I am not referencing that package in any other dependency that I'm aware of, and if I remove the zio-s3 dependency my code compiles and runs just fine.

I'm new to Scala and ZIO, but from what I can see, the problem line appears to be this one https://github.com/zio/zio-s3/blob/main/build.sbt#L46 and this one https://github.com/zio/zio-s3/blob/d90f823af48ca00ee1a14d4d555cdfd9d2b41c4e/project/BuildHelper.scala#L13

**Comment by regis-leray** [comment]
I cannot reproduce your problem
```
sbt new scala/scala3.g8 
```

i changed my sbt build file witht he zio s3 dependency

```
val scala3Version = "3.2.2"

lazy val root = project
  .in(file("."))
  .settings(
    name := "playground-scala3",
    version := "0.1.0-SNAPSHOT",

    scalaVersion := scala3Version,

    libraryDependencies += "dev.zio" %% "zio-s3" % "0.4.2.3" 
    
  )
```

**Comment by regis-leray** [comment]
Please reopen if you have some problem

**Comment by wheatandtares** [comment]
Hmm it must be that one of my other dependencies is pulling ` org.scala-lang.modules:scala-collection-compat _3` transitively then

**Comment by DGolubets** [comment]
I just got this problem.
You can't do `if (scalaVersion.value == ScalaDotty)` because Scala version evolves.

**Comment by regis-leray** [comment]
~~Oki i think i know how to fix it~~

Also the scala dotty version is static not dynamic. It is set here https://github.com/zio/zio-s3/blob/fa3d201ac5838a9b16e8e3501b45b6efe0012058/project/BuildHelper.scala#L13


i dont understand the issue you are facing i was not able to reproduce, can you provide a script [scastie](https://scastie.scala-lang.org/) to reproduce the issue

**Comment by regis-leray** [comment]
I was checking the dependencies of the project , i dont see anything regarding the 
https://repo1.maven.org/maven2/dev/zio/zio-s3_3/0.4.2.4/zio-s3_3-0.4.2.4.pom 
```
org.scala-lang.modules:scala-collection-compat
```

**Comment by regis-leray** [comment]
You can also display the graph of the dependency with dependency tree command

https://www.baeldung.com/scala/sbt-dependency-tree

**Comment by DGolubets** [comment]
You can try https://scastie.scala-lang.org/TY0yKIaDTAygq4GxKtPrIA
It looks like `zio-s3` brings this from `zio-nio`.
Indeed they mention they fix it in newer release: https://github.com/zio/zio-nio/releases/tag/v2.0.1 (but zio-s3 pulls 2.0.0)

**Comment by regis-leray** [comment]
https://github.com/zio/zio-s3/pull/468

**Comment by regis-leray** [comment]
release 0.4.3
