### ISSUE TITLE
no commonPrefixes property that exists in native aws s3 client listObjectsV2 response

### ISSUE THREAD

**Issue by kuzkdmy** [zio/zio-s3#429]
Having such s3 files
client_1/file_1
client_1/file_n
client_2/file_1
client_n/file_n

With zio s3 there is no way to query without fetching all files to get all list of clients
This can be achieved with usage of native s3 client and passing delimiter and retrieve commonPrefixes property from response 

Can be used execute method, but it will luck pagination, so may be make sense to improve a little zio.s3 
Thanks

**Comment by regis-leray** [comment]
Hello, sorry for the late reply :(

You can use options to specify the filtering ListObjectOptions (prefix and delimiter)


https://github.com/zio/zio-s3/blob/series/2.x/zio-s3/src/main/scala/zio/s3/Live.scala#L82

```
final case class ListObjectOptions(
  prefix: Option[String],
  maxKeys: Long,
  delimiter: Option[String],
  starAfter: Option[String]
)


override def listObjects(bucketName: String, options: ListObjectOptions): IO[S3Exception, S3ObjectListing]
```
